# Generated by Django 5.1.4 on 2024-12-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
