# Generated by Django 5.1.4 on 2024-12-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
